---
version: 2
jobs:
  build:
    working_directory: ~/cp-organisations-service
    docker:
      - image: node:8.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Org Dep
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Install staging dependencies
          command: |
            if [ "$CIRCLE_BRANCH" = "staging" ]; then
              yarn add cp-translations@staging
            fi
  test:
    working_directory: ~/cp-organisations-service
    docker:
      - image: node:8.4
    steps:
      - checkout
      - run:
        name: Tests
        command: yarn test
  deploy:
    working_directory: ~/cp-organisations-service
    docker:
      - image: golang:1.6.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
        name: Deploy to K8
        commands: GIT_SHA1=$CIRCLE_SHA1 GIT_BRANCH=$CIRCLE_BRANCH ./.circleci/kube.sh
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
        requires:
          - build
      - deploy:
        requires:
          - test:
            branches:
              only:
                - master
                - staging
